# Generated by Django 2.2.1 on 2019-06-01 17:30

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_name', models.CharField(default='', max_length=200)),
                ('project_members', models.CharField(default='', max_length=200)),
                ('project_mentors', models.CharField(default='', max_length=200)),
                ('sig', models.CharField(choices=[('crypt', 'CRYPT'), ('charge', 'CHARGE'), ('credit', 'CREDIT'), ('chronicle', 'CHRONICLE'), ('clutch', 'CLUTCH'), ('concrete', 'CONCRETE'), ('create', 'CREATE'), ('catalyst', 'CATALYST')], max_length=9)),
                ('year', models.IntegerField(choices=[(2018, 2018), (2019, 2019)], default=2019)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
