# Generated by Django 2.2.1 on 2019-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190601_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_members',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_mentors',
            new_name='mentors',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
