# Generated by Django 2.2 on 2019-06-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_id',
            new_name='id',
        ),
    ]
