# Generated by Django 2.2 on 2019-05-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
