# Generated by Django 2.2 on 2019-05-07 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190508_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publishing_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
