# Generated by Django 2.2 on 2019-05-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190515_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='id',
            new_name='blog_id',
        ),
    ]
