# Generated by Django 2.2 on 2019-05-16 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20190516_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogview',
            name='session',
        ),
        migrations.AlterField(
            model_name='blogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 13, 40, 27, 743410)),
        ),
    ]
