# Generated by Django 2.2 on 2019-06-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20190516_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sig',
        ),
        migrations.DeleteModel(
            name='BlogView',
        ),
    ]
