# Generated by Django 2.2 on 2019-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sigs',
            field=models.ManyToManyField(to='account.SIG'),
        ),
    ]
