# Generated by Django 2.2 on 2019-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190625_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='description',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
