# Generated by Django 2.2 on 2019-06-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_sig_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch_of',
            field=models.IntegerField(default=2020),
        ),
    ]
