# Generated by Django 2.2.3 on 2019-07-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch_of',
            field=models.IntegerField(default=2020, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='sigs',
            field=models.ManyToManyField(editable=False, to='account.SIG'),
        ),
    ]
