# Generated by Django 2.2 on 2019-08-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190731_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch_of',
            field=models.IntegerField(default=2020),
        ),
    ]
