# Generated by Django 2.2 on 2019-08-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190802_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sigs',
            field=models.ManyToManyField(to='account.SIG'),
        ),
    ]
