# Generated by Django 2.2 on 2019-07-30 07:34

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=200)),
                ('contact1_name', models.CharField(default='', max_length=200)),
                ('contact1_number', models.IntegerField(default=0)),
                ('contact2_name', models.CharField(default='', max_length=200)),
                ('contact2_number', models.IntegerField(default=0)),
                ('venue', models.CharField(default='', max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='a')),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('event_time', models.TimeField(default=datetime.time(13, 4, 16, 871358))),
                ('sig', models.CharField(choices=[('Catalyst', 'Catalyst'), ('Chronicle', 'Chronicle'), ('Clutch', 'Clutch'), ('Create', 'Create'), ('Credit', 'Credit'), ('Crypt', 'Crypt')], default='', max_length=12)),
                ('no_people_signedup', models.IntegerField(default=0, editable=False)),
                ('no_people_showedup', models.IntegerField(default=0, editable=False)),
                ('poster_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('roll_no', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('contact_number', models.IntegerField(default=0)),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='', max_length=12)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails')),
            ],
        ),
    ]
