# Generated by Django 2.2.3 on 2019-07-31 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(13, 54, 10, 439942)),
        ),
    ]
