# Generated by Django 2.2 on 2019-07-31 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190731_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(23, 43, 13, 211497)),
        ),
        migrations.AlterField(
            model_name='team',
            name='member2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='member3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
