# Generated by Django 2.2 on 2019-08-01 02:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20190731_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='contact1_name',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='contact1_number',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='contact2_name',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='contact2_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='attendance',
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='contact1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='contact2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(8, 0, 25, 343729)),
        ),
    ]
