# Generated by Django 2.2 on 2019-08-08 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190808_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(11, 9, 40, 380752)),
        ),
    ]
