# Generated by Django 2.2.4 on 2019-08-10 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20190810_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(5, 2, 18, 386868)),
        ),
    ]
