# Generated by Django 2.2 on 2019-09-05 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20190905_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='members',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(8, 10, 34, 753239)),
        ),
    ]
