# Generated by Django 2.2 on 2019-09-05 05:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20190905_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('participant1', models.CharField(max_length=50)),
                ('participant2', models.CharField(max_length=50)),
                ('participant3', models.CharField(max_length=50)),
                ('participant4', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('phone2', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ThreeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('participant1', models.CharField(max_length=50)),
                ('participant2', models.CharField(max_length=50)),
                ('participant3', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('phone2', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(10, 55, 6, 586237)),
        ),
    ]
