# Generated by Django 2.2 on 2019-09-05 05:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20190905_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourmember',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails'),
        ),
        migrations.AddField(
            model_name='threemember',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(11, 1, 18, 484507)),
        ),
    ]
