# Generated by Django 2.2 on 2019-09-05 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20190905_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(17, 51, 33, 420519)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='sig',
            field=models.CharField(choices=[('Catalyst', 'Catalyst'), ('Chronicle', 'Chronicle'), ('Clutch', 'Clutch'), ('Create', 'Create'), ('Credit', 'Credit'), ('Crypt', 'Crypt'), ('Club', 'Club')], default='', max_length=12),
        ),
    ]
