# Generated by Django 2.2.6 on 2019-10-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20190905_1751'),
        ('events', '0026_auto_20190905_0552'),
    ]

    operations = [
    ]
