# Generated by Django 2.2.6 on 2019-10-10 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_merge_20191010_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(19, 14, 11, 993841)),
        ),
    ]
