# Generated by Django 2.2.4 on 2019-10-26 08:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20191011_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(8, 22, 21, 210029)),
        ),
        migrations.CreateModel(
            name='OneMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('participant1', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails')),
            ],
        ),
    ]
