# Generated by Django 2.2.8 on 2019-12-18 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20191208_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onemember',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(13, 47, 49, 894513)),
        ),
        migrations.AlterField(
            model_name='fourmember',
            name='participant4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='threemember',
            name='participant3',
            field=models.CharField(default='', max_length=50),
        ),
    ]
