# Generated by Django 2.2.8 on 2020-01-15 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20191226_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(16, 24, 2, 881805)),
        ),
    ]
