# Generated by Django 2.2.8 on 2020-01-23 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_auto_20200123_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(18, 7, 1, 21364)),
        ),
    ]
