# Generated by Django 2.2 on 2019-06-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SIG'),
        ),
    ]
