# Generated by Django 2.2 on 2019-06-21 11:10

import datetime
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(choices=[('2nd year', '2nd year'), ('3rd year', '3rd year')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Round0Question',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(blank=True)),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='SIGRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
                ('round_number', models.IntegerField(default=1)),
                ('round_description', models.CharField(max_length=500)),
                ('criteria', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=None)),
                ('question', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True)),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Applicant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Round0Question')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_completed', models.IntegerField(default=0)),
                ('qualified_for_next', models.BooleanField(default=False)),
                ('next_round_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 21, 16, 40, 11, 503648), null=True)),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Applicant')),
            ],
        ),
    ]
