<<<<<<< HEAD
# Generated by Django 2.2 on 2019-06-18 08:11

from django.db import migrations, models
=======
# Generated by Django 2.2.1 on 2019-06-18 16:55

from django.db import migrations, models
import phonenumber_field.modelfields
>>>>>>> fc5014123bf93ac65610d1fb1d52524d45f940e5


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='ApplicantPasscode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(default='', max_length=100)),
                ('applicant_passcode', models.CharField(default='', max_length=100)),
=======
            name='Applicant',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(choices=[('2nd year', '2nd year'), ('3rd year', '3rd year')], max_length=8)),
>>>>>>> fc5014123bf93ac65610d1fb1d52524d45f940e5
            ],
        ),
    ]
