# Generated by Django 2.2.1 on 2019-06-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0002_auto_20190618_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.TextField(blank=True)),
                ('progress', models.IntegerField(default=0)),
                ('qualified_for_next', models.BooleanField(default=False)),
                ('next_round_time', models.DateField(null=True)),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Applicant')),
            ],
        ),
    ]
