# Generated by Django 2.2.1 on 2019-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0003_applicantresponses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIGRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
                ('round_number', models.IntegerField(default=1)),
                ('round_description', models.CharField(max_length=500)),
            ],
        ),
    ]
