# Generated by Django 2.2 on 2019-06-19 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0003_auto_20190619_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponses',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 19, 9, 12, 11, 375140, tzinfo=utc)),
        ),
    ]
