# Generated by Django 2.2.1 on 2019-06-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0004_siground'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(blank=True)),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
            ],
        ),
    ]
