# Generated by Django 2.2 on 2019-06-19 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0006_auto_20190619_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponses',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 19, 9, 21, 57, 409935, tzinfo=utc)),
        ),
    ]
