# Generated by Django 2.2 on 2019-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0007_auto_20190619_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponses',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=1560936183.1108625),
        ),
    ]
