# Generated by Django 2.2 on 2019-06-19 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0010_auto_20190619_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponses',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 19, 15, 9, 14, 204533)),
        ),
    ]
