# Generated by Django 2.2 on 2019-06-20 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0012_auto_20190619_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponses',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 12, 48, 32, 995824), null=True),
        ),
    ]
