# Generated by Django 2.2 on 2019-06-20 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0013_auto_20190620_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantresponses',
            name='next_round_time',
        ),
        migrations.RemoveField(
            model_name='applicantresponses',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='applicantresponses',
            name='qualified_for_next',
        ),
        migrations.RemoveField(
            model_name='applicantresponses',
            name='sig',
        ),
        migrations.CreateModel(
            name='ApplicantProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('qualified_for_next', models.BooleanField(default=False)),
                ('next_round_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 14, 3, 16, 287289), null=True)),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Applicant')),
            ],
        ),
    ]
