# Generated by Django 2.2 on 2019-06-20 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0015_auto_20190620_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 14, 19, 16, 821318), null=True),
        ),
    ]
