# Generated by Django 2.2 on 2019-06-20 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0016_auto_20190620_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantprogress',
            old_name='progress',
            new_name='round_completed',
        ),
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 14, 33, 16, 860403), null=True),
        ),
    ]
