# Generated by Django 2.2 on 2019-06-20 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0017_auto_20190620_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 16, 20, 0, 67337), null=True),
        ),
    ]
