# Generated by Django 2.2 on 2019-06-21 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0019_auto_20190621_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 21, 12, 56, 23, 868483), null=True),
        ),
    ]
