# Generated by Django 2.2 on 2019-06-21 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0022_auto_20190621_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 21, 13, 22, 8, 809857), null=True),
        ),
    ]
