# Generated by Django 2.2.8 on 2020-01-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obscura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='hard',
            new_name='hard_un',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='med',
            new_name='med_un',
        ),
        migrations.RemoveField(
            model_name='team',
            name='easy',
        ),
        migrations.RemoveField(
            model_name='team',
            name='subs',
        ),
        migrations.AddField(
            model_name='team',
            name='easy_subs',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='hard_subs',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='med_subs',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
