# Generated by Django 2.2.8 on 2020-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obscura', '0002_auto_20200130_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='easy_subs',
            field=models.CharField(default="['*','*','*','*','*','*','*']", max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='hard_subs',
            field=models.CharField(default="['*','*','*','*','*','*','*']", max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='med_subs',
            field=models.CharField(default="['*','*','*','*','*','*','*']", max_length=200),
        ),
    ]
