# Generated by Django 2.2.8 on 2020-01-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obscura', '0003_auto_20200130_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='finish_time',
            field=models.CharField(default='*', max_length=100),
        ),
    ]
