# Generated by Django 2.2 on 2019-06-26 19:35

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('categories', models.CharField(default='', max_length=200)),
                ('abstract', models.CharField(default='', max_length=200)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('publishing_date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
