# Generated by Django 2.2 on 2019-06-28 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_bloghits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloghits',
            name='session',
        ),
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 13, 59, 32, 618158)),
        ),
    ]
