# Generated by Django 2.2.3 on 2019-07-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20190722_1712'),
        ('blogs', '0014_auto_20190722_1255'),
    ]

    operations = [
    ]
