# Generated by Django 2.2 on 2019-07-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20190724_0749'),
        ('blogs', '0015_merge_20190723_1026'),
    ]

    operations = [
    ]
