# Generated by Django 2.2 on 2019-08-02 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_auto_20190801_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 12, 59, 4, 774757)),
        ),
    ]
