# Generated by Django 2.2 on 2019-08-02 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_auto_20190802_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 13, 55, 21, 63772)),
        ),
    ]
