# Generated by Django 2.2 on 2019-08-08 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0034_auto_20190808_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 11, 9, 40, 415540)),
        ),
    ]
