# Generated by Django 2.2 on 2019-08-08 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0035_auto_20190808_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 11, 10, 16, 192408)),
        ),
    ]
