# Generated by Django 2.2 on 2019-08-08 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0036_auto_20190808_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 11, 37, 50, 440484)),
        ),
    ]
