# Generated by Django 2.2 on 2019-08-08 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0038_auto_20190808_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 11, 56, 37, 451395)),
        ),
    ]
