# Generated by Django 2.2 on 2019-08-08 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0039_auto_20190808_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 12, 12, 3, 726294)),
        ),
    ]
