# Generated by Django 2.2.4 on 2019-08-10 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0041_auto_20190810_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 5, 2, 18, 398327)),
        ),
    ]
