# Generated by Django 2.2 on 2019-09-05 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0043_auto_20190816_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 8, 9, 15, 979048)),
        ),
    ]
