# Generated by Django 2.2.6 on 2019-10-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_auto_20190905_0552'),
        ('blogs', '0048_auto_20190905_1751'),
    ]

    operations = [
    ]
