# Generated by Django 2.2.6 on 2019-10-10 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0049_merge_20191010_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 19, 14, 12, 3807)),
        ),
    ]
