# Generated by Django 2.2.6 on 2019-10-10 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0050_auto_20191010_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 19, 39, 15, 794434)),
        ),
    ]
