# Generated by Django 2.2.4 on 2019-10-26 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0052_auto_20191011_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 8, 22, 21, 222743)),
        ),
    ]
