# Generated by Django 2.2.4 on 2019-10-26 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0053_auto_20191026_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 9, 55, 58, 440635)),
        ),
    ]
