# Generated by Django 2.2.4 on 2019-10-26 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0054_auto_20191026_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 10, 0, 5, 816705)),
        ),
    ]
