# Generated by Django 2.2.8 on 2019-12-08 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0056_auto_20191026_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 5, 4, 44, 982667)),
        ),
    ]
