# Generated by Django 2.2.8 on 2019-12-18 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0057_auto_20191208_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 13, 47, 49, 904196)),
        ),
    ]
