# Generated by Django 2.2.4 on 2019-12-26 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0058_auto_20191218_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 13, 21, 20, 200468)),
        ),
    ]
