# Generated by Django 2.2.8 on 2020-01-15 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0059_auto_20191226_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 16, 24, 2, 891577)),
        ),
    ]
