# Generated by Django 2.2.8 on 2020-01-23 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0062_auto_20200123_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 18, 7, 1, 31136)),
        ),
    ]
