# Generated by Django 2.2.4 on 2020-01-28 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0075_auto_20200128_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 18, 50, 19, 836941)),
        ),
    ]
