# Generated by Django 2.2.9 on 2020-01-28 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0078_auto_20200128_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 19, 23, 22, 470491)),
        ),
    ]
