# Generated by Django 2.2.9 on 2020-01-28 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0079_auto_20200128_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 19, 26, 33, 354803)),
        ),
    ]
