# Generated by Django 2.2.8 on 2020-01-30 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0079_auto_20200130_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 9, 59, 48, 192929)),
        ),
    ]
