# Generated by Django 2.2.8 on 2020-01-30 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0080_auto_20200130_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 10, 2, 36, 606325)),
        ),
    ]
