# Generated by Django 2.2.8 on 2020-01-30 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0081_auto_20200130_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 10, 7, 18, 932776)),
        ),
    ]
