# Generated by Django 2.2.4 on 2020-01-31 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0082_auto_20200130_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 17, 54, 25, 390485)),
        ),
    ]
