# Generated by Django 2.2.6 on 2019-10-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptober', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='input1',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='input2',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='input3',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='input4',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='input5',
            field=models.CharField(default='[]', max_length=100),
        ),
    ]
