# Generated by Django 2.2 on 2019-06-26 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0002_auto_20190626_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 26, 16, 55, 56, 859178), null=True),
        ),
    ]
