# Generated by Django 2.2 on 2019-06-26 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0002_auto_20190627_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Applicant')),
            ],
        ),
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 27, 1, 12, 6, 392573), null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.ApplicantResponse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.ApplicantResponse'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
