# Generated by Django 2.2 on 2019-06-24 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0004_auto_20190624_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 24, 14, 17, 22, 691607), null=True),
        ),
    ]
