# Generated by Django 2.2 on 2019-06-24 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0005_auto_20190624_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 24, 15, 5, 2, 714238), null=True),
        ),
    ]
