# Generated by Django 2.2 on 2019-06-26 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0006_auto_20190627_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 27, 1, 18, 56, 57344), null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='response',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recruitments.ApplicantResponse'),
        ),
    ]
