# Generated by Django 2.2 on 2019-06-26 19:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0008_auto_20190627_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='rollno',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Roll number must be in the format: 1[7/8]1XX[1/2]XX', regex='^1[78]1(IT|MN|MT|ME|CS|EE|EC|CH|D)[12][0-7][0-9]$')]),
        ),
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 27, 1, 24, 58, 253263), null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='response',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recruitments.ApplicantResponse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recruitments.ApplicantResponse'),
        ),
    ]
