# Generated by Django 2.2 on 2019-06-24 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0008_auto_20190624_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 24, 16, 0, 7, 322565), null=True),
        ),
    ]
