# Generated by Django 2.2 on 2019-06-24 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0010_auto_20190624_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 24, 16, 10, 49, 533799), null=True),
        ),
    ]
