# Generated by Django 2.2 on 2019-06-26 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitments', '0010_auto_20190627_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True)),
                ('sig', models.CharField(default='', max_length=9)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Applicant')),
            ],
        ),
        migrations.RemoveField(
            model_name='interview',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='applicantresponse',
            name='body',
        ),
        migrations.RemoveField(
            model_name='siground',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='siground',
            name='questions',
        ),
        migrations.AddField(
            model_name='applicantresponse',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recruitments.Question'),
        ),
        migrations.AddField(
            model_name='applicantresponse',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicantresponse',
            name='sig',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='criteria',
            name='sig',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recruitments.SIGRound'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='sig',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recruitments.SIGRound'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ApplicantProgress',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='criteria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recruitments.Criteria'),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
