# Generated by Django 2.2 on 2019-06-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0011_auto_20190627_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Question'),
        ),
        migrations.AlterField(
            model_name='interviewresponse',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Criteria'),
        ),
    ]
