# Generated by Django 2.2 on 2019-06-24 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0011_auto_20190624_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True)),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True)),
                ('sig', models.CharField(choices=[('Crypt', 'CRYPT'), ('Charge', 'CHARGE'), ('Credit', 'CREDIT'), ('Chronicle', 'CHRONICLE'), ('Clutch', 'CLUTCH'), ('Concrete', 'CONCRETE'), ('Create', 'CREATE'), ('Catalyst', 'CATALYST')], max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='siground',
            name='question',
        ),
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 24, 19, 39, 39, 951762), null=True),
        ),
        migrations.AlterField(
            model_name='applicantresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Question'),
        ),
        migrations.RemoveField(
            model_name='siground',
            name='criteria',
        ),
        migrations.DeleteModel(
            name='Round0Question',
        ),
        migrations.AddField(
            model_name='siground',
            name='questions',
            field=models.ManyToManyField(to='recruitments.Question'),
        ),
        migrations.AddField(
            model_name='siground',
            name='criteria',
            field=models.ManyToManyField(to='recruitments.Criteria'),
        ),
    ]
