# Generated by Django 2.2 on 2019-06-25 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0013_auto_20190625_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogress',
            name='next_round_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 25, 14, 25, 8, 233403), null=True),
        ),
    ]
