# Generated by Django 2.2 on 2019-06-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0015_auto_20190627_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprogress',
            name='interview_done',
            field=models.BooleanField(default=False),
        ),
    ]
