# Generated by Django 2.2 on 2019-06-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0016_applicantprogress_interview_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.SIGRound'),
        ),
    ]
