# Generated by Django 2.2 on 2019-06-28 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0017_auto_20190627_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='rollno',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Roll number must be in the format: 1[7/8]1XX[1/2]XX', regex='^1[78]1(IT|MN|MT|ME|CS|EE|EC|CH|CV)[12][0-7][0-9]$')]),
        ),
    ]
