# Generated by Django 2.2 on 2019-06-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0018_auto_20190628_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantresponse',
            name='sig',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='sig',
        ),
        migrations.RemoveField(
            model_name='interviewresponse',
            name='sig',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sig',
        ),
        migrations.AddField(
            model_name='applicantresponse',
            name='sig_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitments.SIGRound'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteria',
            name='sig_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitments.SIGRound'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='sig_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitments.SIGRound'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='sig_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitments.SIGRound'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicantprogress',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SIG'),
        ),
        migrations.AlterField(
            model_name='siground',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SIG'),
        ),
    ]
