# Generated by Django 2.2 on 2019-08-08 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0021_auto_20190804_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='rollno',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Roll number must be in the format: 1[7/8]1XX[1/2]XX', regex='^1[78]1(IT|CV|MN|MT|ME|CS|EE|EC|CH|CV|CO)[012][0-9][0-9]$')]),
        ),
    ]
