# Generated by Django 2.2 on 2019-08-08 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0022_auto_20190808_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantFormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.Applicant')),
                ('form', models.ManyToManyField(to='recruitments.ApplicantResponse')),
                ('sig_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.SIGRound')),
            ],
        ),
    ]
