# Generated by Django 2.2 on 2019-08-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0023_applicantformresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresponse',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ApplicantFormResponse',
        ),
    ]
