# Generated by Django 2.2 on 2019-08-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0024_auto_20190808_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
