# Generated by Django 2.2 on 2019-08-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0025_auto_20190808_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
