# Generated by Django 2.2.4 on 2020-01-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_auto_20200131_1747'),
        ('meet', '0014_auto_20200130_1007'),
    ]

    operations = [
    ]
