# Generated by Django 2.2 on 2019-05-12 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='abstract',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='categories',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='publishing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
