# Generated by Django 2.2 on 2019-05-12 08:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190512_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='a'),
        ),
    ]
