# Generated by Django 2.2 on 2019-05-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventdetails_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetails',
            old_name='abstract',
            new_name='contact1_name',
        ),
        migrations.RenameField(
            model_name='eventdetails',
            old_name='categories',
            new_name='contact1_number',
        ),
        migrations.RenameField(
            model_name='eventdetails',
            old_name='title',
            new_name='contact2_name',
        ),
        migrations.RenameField(
            model_name='eventdetails',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='eventdetails',
            old_name='publishing_date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='views',
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='contact2_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='event_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='sig',
            field=models.CharField(choices=[('Catalyst', 'Catalyst'), ('Chronicle', 'Chronicle'), ('Clutch', 'Clutch'), ('Create', 'Create'), ('Credit', 'Credit'), ('Crypt', 'Crypt')], default='', max_length=12),
        ),
    ]
