# Generated by Django 2.2 on 2019-05-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190512_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetails',
            old_name='author',
            new_name='venue',
        ),
    ]
