# Generated by Django 2.2 on 2019-05-12 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190512_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(8, 34, 40, 816177)),
        ),
    ]
