# Generated by Django 2.2 on 2019-05-12 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventdetails_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='no_people_showedup',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='no_people_signedup',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='poster_image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='contact1_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='contact2_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(13, 7, 13, 507843)),
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('roll_no', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('contact_number', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails')),
            ],
        ),
    ]
