# Generated by Django 2.2 on 2019-05-12 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190512_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.TimeField(default=datetime.time(13, 11, 17, 707801)),
        ),
    ]
